//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTSharp.Maui.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IoTSharp.Maui.Resources.Strings.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
       
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string Dark_Mode
        {
            get
            {
                return ResourceManager.GetString("Dark_Mode", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Wifi only.
        /// </summary>
        internal static string Only_Wifi
        {
            get
            {
                return ResourceManager.GetString("Only_Wifi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable or disable dark mode.
        /// </summary>
        internal static string Semantic_Description_Toggle_Mode
        {
            get
            {
                return ResourceManager.GetString("Semantic_Description_Toggle_Mode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable or disable wifi settings.
        /// </summary>
        internal static string Semantic_Description_Toggle_Wifi
        {
            get
            {
                return ResourceManager.GetString("Semantic_Description_Toggle_Wifi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcasts demo App developed in MAUI.
        /// </summary>
        internal static string Settings_Info {
            get {
                return ResourceManager.GetString("Settings_Info", resourceCulture);
            }
        }
               
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What’s new.
        /// </summary>
        internal static string Whats_New {
            get {
                return ResourceManager.GetString("Whats_New", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  IoTSharp settings.
        /// </summary>
        internal static string IoTSharp_Settings
        {
            get
            {
                return ResourceManager.GetString("IoTSharp_Settings", resourceCulture);
            }
        }


    }
}
